---
- name: Install packages
  ansible.builtin.dnf:
    name:
      - git-core
      - pre-commit
      - libatomic # required by prettier check with Node.js >= 25.0.0
  become: true

- name: Run pre-commit
  ansible.builtin.command: pre-commit run --all-files --hook-stage manual --verbose
  args:
    chdir: "{{ zuul.project.src_dir }}"
  register: pc_result
  changed_when: "pc_result.rc == 1"
